# Generated by Django 4.2.7 on 2025-11-10 12:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='完整的手機號碼，包含國碼（例如：+886987654321）', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='手機號碼格式應為：+國碼號碼（例如：+886987654321）', regex='^\\+\\d{1,3}\\d{4,14}$')], verbose_name='手機號碼')),
                ('phone_verified', models.BooleanField(default=False, help_text='使用者是否已完成手機號碼驗證', verbose_name='手機已驗證')),
                ('otp_attempts', models.IntegerField(default=0, help_text='當前 verification session 的驗證嘗試次數（最多3次）', verbose_name='OTP 嘗試次數')),
                ('verification_status', models.CharField(blank=True, choices=[('OTP_SENT', 'OTP 已發送'), ('OTP_RESENT', 'OTP 已重新發送'), ('VERIFIED', '已驗證'), ('INVALID_OTP', '驗證碼錯誤'), ('LOCKED', '已鎖定（錯誤次數過多）'), ('TOO_MANY_REQUESTS', '請求過於頻繁')], help_text='當前的手機驗證狀態', max_length=20, null=True, verbose_name='驗證狀態')),
                ('verification_id', models.CharField(blank=True, help_text='Firebase 返回的驗證 session ID', max_length=255, null=True, verbose_name='Firebase Verification ID')),
                ('last_otp_sent_at', models.DateTimeField(blank=True, help_text='最後一次發送 OTP 的時間戳記', null=True, verbose_name='最後發送時間')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者列表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('action', models.CharField(choices=[('SEND', '發送 OTP'), ('RESEND', '重新發送 OTP'), ('VERIFY_SUCCESS', '驗證成功'), ('VERIFY_FAILED', '驗證失敗')], max_length=20, verbose_name='操作類型')),
                ('verification_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verification ID')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'OTP 驗證記錄',
                'verbose_name_plural': 'OTP 驗證記錄列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
